import { memo } from 'react';
import {
  Home,
  Music,
  Music2,
  Calendar,
  Users,
  Wrench,
  BookOpen,
  Package,
  Settings as SettingsIcon,
  GraduationCap,
  User,
  Search,
  Bell,
  Sun,
  Moon,
  Monitor,
  X,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Hand,
  Upload,
  Download,
  FileText,
  ListMusic,
  PartyPopper,
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  Check,
  ClipboardList,
  Folder,
  Smartphone,
  Mic,
  MicOff,
  Lock,
  AlertTriangle,
  Link as LinkIcon,
  RotateCw,
  Cloud,
  CloudOff,
  Heart,
  Plus,
  LogOut,
  Paperclip,
  Square,
  MessageCircle,
  Drama,
  Armchair,
  Battery,
  BatteryLow,
  WifiOff,
  Webhook,
  BarChart3,
  Laptop,
  Globe,
  Bookmark,
  Send,
  Play,
  Pause,
  Clock,
  Info,
  Archive,
  MousePointer2,
  Highlighter,
  Type,
  Stamp,
  Eraser,
  Shapes,
  Undo2,
  Redo2,
  Circle,
  Minus,
  ArrowRight,
  PenTool,
  MessageSquare,
  ChevronLeft,
  ZoomIn,
  ZoomOut,
  Move,
  Maximize2,
  Minimize2,
  StopCircle,
  ArrowLeft,
  MapPin,
  Truck,
  Building2,
  CreditCard,
  Mail,
  Shield,
  CheckCircle,
  XCircle,
  HelpCircle,
  type LucideIcon,
} from 'lucide-react';

const iconMap = {
  home: Home,
  music: Music,
  music2: Music2,
  calendar: Calendar,
  users: Users,
  wrench: Wrench,
  book: BookOpen,
  package: Package,
  settings: SettingsIcon,
  graduationCap: GraduationCap,
  user: User,
  search: Search,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  close: X,
  menu: Menu,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  hand: Hand,
  upload: Upload,
  download: Download,
  fileText: FileText,
  listMusic: ListMusic,
  partyPopper: PartyPopper,
  pencil: Pencil,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  clipboard: ClipboardList,
  folder: Folder,
  smartphone: Smartphone,
  mic: Mic,
  micOff: MicOff,
  lock: Lock,
  warning: AlertTriangle,
  link: LinkIcon,
  refresh: RotateCw,
  cloud: Cloud,
  cloudOff: CloudOff,
  heart: Heart,
  plus: Plus,
  logout: LogOut,
  paperclip: Paperclip,
  square: Square,
  message: MessageCircle,
  drama: Drama,
  chair: Armchair,
  battery: Battery,
  batteryLow: BatteryLow,
  wifiOff: WifiOff,
  webhook: Webhook,
  chart: BarChart3,
  laptop: Laptop,
  globe: Globe,
  bookmark: Bookmark,
  send: Send,
  play: Play,
  pause: Pause,
  clock: Clock,
  info: Info,
  archive: Archive,
  mousePointer: MousePointer2,
  highlighter: Highlighter,
  type: Type,
  stamp: Stamp,
  eraser: Eraser,
  shapes: Shapes,
  undo: Undo2,
  redo: Redo2,
  circle: Circle,
  line: Minus,
  arrow: ArrowRight,
  penTool: PenTool,
  MessageSquare: MessageSquare,
  PenTool: PenTool,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  move: Move,
  maximize: Maximize2,
  minimize: Minimize2,
  stop: StopCircle,
  arrowLeft: ArrowLeft,
  mapPin: MapPin,
  truck: Truck,
  building: Building2,
  creditCard: CreditCard,
  envelope: Mail,
  shield: Shield,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  helpCircle: HelpCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

interface IconProps {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
  'aria-hidden'?: boolean;
}

export const Icon = memo(function Icon({ name, size = 20, strokeWidth = 2, className, style, ...rest }: IconProps) {
  const Component = iconMap[name];
  if (!Component) return null;
  return (
    <Component
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
      aria-hidden={rest['aria-hidden'] ?? true}
    />
  );
});
